export const actions = {
  profile: {
    DATA_FETCHING: "PROFILT_DATA_FETCHING",
    DATA_FETCHED: "PROFILT_DATA_FETCHED",
    DATA_FETCH_ERROR: "PROFILT_DATA_FETCH_ERROR",
    USER_DATA_EDITED: "PROFILE_USER_DATA_EDITED",
    IMAGE_UPDATAED: "PROFILE_IMAGE_UPDATED",
  },
};
