export const actions = {
  profile: {
    DATA_FETCHING: "PROFILT_DATA_FETCHING",
    DATA_FETCHED: "PROFILT_DATA_FETCHED",
    DATA_FETCH_ERROR: "PROFILT_DATA_FETCH_ERROR",
    USER_DATA_EDITED: "PROFILE_USER_DATA_EDITED",
    IMAGE_UPDATAED: "PROFILE_IMAGE_UPDATED",
  },
  post: {
    DATA_FETCHING: "POST_DATA_FETCHING",
    DATA_FETCHED: "POST_DATA_FETCHED",
    DATA_FETCH_ERROR: "POST_DATA_FETCH_ERROR",
    DATA_EDITED: "POST_DATA_EDITED",
    POST_DELETED: "POST_DATA_DELETED",
    POST_LIKED: "POST_LIKED",
    POST_COMMENTED: "POST_COMMENTED",
  },
};
